### ISSUE TITLE
Enhancement / New feature : Pre and Post scripts

### ISSUE THREAD

**Issue by veragini** [dbcrossbar/dbcrossbar#183]
Not sure if it has been discussed or planned, but it would be great to have a pre and post option to be used so we could pass a pre and post script like setting 
SET session_replication_role = replica;	as a Pre script of a dbcrossbar cp or to disable triggers and so once finished a Post custom script to enable the given table triggers.

**Comment by emk** [comment]
For this use case, I would recommend calling `psql` before and after `dbcrossbar`. In general, `dbcrossbar` focuses as closely as possible on copying tables as accurately as it can between two databases. Data cleaning, creation of unusual column types, and similar features are out of scope, because we want to do one thing well.

`pgloader` is often a good choice if you need to have complex or customized imports into PostgreSQL. It might be possible to dump the data to CSV using `dbcrossbar`, and load it using `pgloader`.
