### ISSUE TITLE
Timestamp formats expect 6 digits for microseconds when 3 digits seems to be the standard

### ISSUE THREAD

**Issue by blakew** [dbcrossbar/dbcrossbar#191]
Got this error on a cp:

```
Error while reading data, error message: 

Could not parse '2021-06-30 08:33:37.000 -0700' as TIMESTAMP for field created_at__utc_ (position 2) starting at location 661  with message 

'Could not parse '2021-06-30 08:33:37.000 -0700' as a timestamp. Required format is YYYY-MM-DD HH:MM[:SS[.SSSSSS]] or YYYY/MM/DD HH:MM[:SS[.SSSSSS]]'
```

Based on [moment.js docs](https://momentjs.com/docs/#/parsing/special-formats/) it does seem `YYYY-MM-DDTHH:mm:ss.SSS` is a standard format for timestamps. Can it be supported?

**Comment by emk** [comment]
@blakew What are your source and destination databases (just the types like "postgres:" or "bigquery:", not the actual URLs)? This looks like a driver-specific problem.

**Comment by emk** [comment]
The most likely problem is you field is named `created_at__utc_`, but it includes a `-0700` timezone offset in `'2021-06-30 08:33:37.000 -0700'`, which is definitely not UTC! `dbcrossbar` supports two different column types, `timestamp_without_time_zone` and `timestamp_with_time_zone`. My guess is that you're getting this error not because of how many digits of milliseconds you're passing (.SSS versus .SSSSSS), but because your data is in `timestamp_with_time_zone` format and you're trying to store it in a `timestamp_without_time_zone` column. The underlying destination database (whatever that is) is rejecting it because of this mismatch.

**Comment by blakew** [comment]
source = snowflake
destination = BigQuery

**Comment by emk** [comment]
Yes, this is an issue with a mismatch between the destination schema and the CSV data. BigQuery is not required to accept timezones for a column of type `timestamp_without_time_zone` (or `TIMESTAMP` in BigQuery's terminology).
